### ISSUE TITLE
Automatically typoscript includes does not work

### ISSUE THREAD

**Issue by marvinhuebner** [Yoast/Yoast-SEO-for-TYPO3#128]
I have to add the typoscript manually in my template extension to make the extension working.

Otherwise i got the following error in the page module:
```
We got an error 503 (Service Unavailable) when requesting https://project.local/index.php?id=2&type=1480321830&L=0 to analyse your content. Please check your javascript console for more information.
```

And this is causing because the requested page shows:

```
#1294587217: The page is not configured! [type=1480321830][]. This means that there is no TypoScript object of type PAGE with typeNum=1480321830 configured. (More information)

TYPO3\CMS\Core\Error\Http\ServiceUnavailableException thrown in file
/httpdocs/project/vendor/typo3/cms/typo3/sysext/frontend/Classes/Controller/TypoScriptFrontendController.php in line 2475.
```

yoast_seo: 1.3.0
TYPO3: 8.7.8

**Comment by einpraegsam** [comment]
Same here. 
The problem is located in https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/ext_localconf.php#L15 and in https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/ext_localconf.php#L21. It simply works if the fourth parameter for addTypoScript() is empty instead of `defaultContentRendering`.
