### ISSUE TITLE
No image on this page even if an image is stored in page.media

### ISSUE THREAD

**Issue by stat1x** [Yoast/Yoast-SEO-for-TYPO3#157]
Hi,
In the content analyzer I've got a message telling me that my page has no image event if I've added some image in the page.media field.
Could it be fixed?
Thanks for fantastic job guys!
Jay

**Comment by haassie** [comment]
Thanks for your report. I think this issue is the same as #134. We are currently investigating a solution to check the complete output of the page, but it should be a solution that works in all cases so that makes it a little bit complicated. We will continue on issue #134. If you want you can subscribe to that issue to get updates as well.

**Comment by stat1x** [comment]
Oh thanks for feedback, I will have a look at #134 then.
