### ISSUE TITLE
Error Message in Log

### ISSUE THREAD

**Issue by Shentao83** [Yoast/Yoast-SEO-for-TYPO3#208]
* TYPO3 version: 7.6.30
* Yoast SEO version: 3.0.2
* PHP version: 5.5.9

My log is flooded with these 2 alternating error messages:

`Core: Error handler (FE): PHP Warning: array_filter() expects at most 2 parameters, 3 given in /home/xxx/xxx/xxx/typo3conf/ext/yoast_seo/Classes/Frontend/PageRenderer/PageMetaRenderer.php line 104`

`Core: Error handler (FE): PHP Warning: Invalid argument supplied for foreach() in /home/xxx/xxx/xxx/typo3conf/ext/yoast_seo/Classes/Frontend/PageRenderer/PageMetaRenderer.php line 41`

I have no idea what the problem is. Other than this error log, everything else, including Yoast works fine (as far as I can tell)

**Comment by RinyVT** [comment]
The first one: the third parameter of array_filter has been introduced in PHP 5.6, PHP 5.5 is EOL so I don't think we'll fix that / make a condition based on PHP version. My advice would be to update your PHP version to at least 5.6 but preferably 7.x, because your PHP version is almost 4,5 years old (release date 6 Feb 2014)

Second error: Are you sure the typoscript of yoast has been included? Because it reads from the view->variables which is defined in Configuration/TypoScript/Setup/Module.typoscript

**Comment by Shentao83** [comment]
If I take a look at the template analyzer, the Yoast Typoscript has been definitely included in SYS:TYPO3_CONF_VARS:FE:defaultTypoScript  

I guess that it is the old PHP, then! I will try to upgrade to 5.6 and then later on to 7.2. I guess that this will fix this. 

Thank you for your swift feedback!

**Comment by RinyVT** [comment]
Okay, let me/us know if that fixes the issue!
Be careful with the PHP-update, to 5.6 should cause no problems but if you upgrade to 7.x it could raise some issues, especially with third-party extensions which may or may not be compatible.

**Comment by Shentao83** [comment]
Hi RinyVT, yes, PHP 5.5.x was definitely the reason of this error. Good to know! Thank you for your help.
