### ISSUE TITLE
Use yoast fields in own extension

### ISSUE THREAD

**Issue by shorenkamp** [Yoast/Yoast-SEO-for-TYPO3#211]
I have a problem with the integration in my own extension. I tried the example given in the manual with news. But it works not 100% correct

I used
'tx_yoastseo_snippetpreview' => [
          'label' => $llPrefix . 'snippetPreview',
          'exclude' => true,
          'displayCond' => 'REC:neu:false',
          'config' => [
              'type' => 'text',
              'renderType' => 'snippetPreview',
              'settings' => [
                  'titleField' => 'browser_title',
                  'descriptionField' => 'meta_description'
              ]
          ]
      ],

but the settings are ignored. It always used the first found text on the page
and the length check for Title and Description is not working. 

The fields are in the same TCA tab and the link in the snippet is correct. I used yoast_seo Version 3.0.4 and TYPO3 8.7.19.

This is the page which I want to check: https://www.laudius.de/kurs/altgriechisch

And in the BackEnd it looks 
![firefox_screenshot_2018-08-31t07-48-43 327z](https://user-images.githubusercontent.com/29160734/44899800-0ed2c000-ad03-11e8-8c4b-668492fdbc2b.png)

Kind ragards
Stefan

**Comment by RinyVT** [comment]
I'm going to close this ticket due to the age of the issue.
We're currently on version 8.1.0 of the extension and I hope/expect that this issue has long been resolved.

If someone finds this issue, I've updated the documentation with up-to-date information on how to implement the Yoast SEO functionalities in your own extension:
https://docs.typo3.org/p/yoast-seo-for-typo3/yoast_seo/master/en-us/Configuration/OtherPlugins/Index.html

Feel free to open a new issue if you encounter more/other problems.

**Comment by sfroemkenjw** [comment]
Instead of `REC:neu:false` it should be `REC:new:false`
