### ISSUE TITLE
Preview shnippet shows raw HTML

### ISSUE THREAD

**Issue by mweber1973** [Yoast/Yoast-SEO-for-TYPO3#251]
* [x ] I've read and understood the [contribution guidelines](https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/.github/CONTRIBUTING.md).
* [ x] I've searched for any related issues and avoided creating a duplicate issue.

Clicking the "readability" or "SEO" link shows raw html-code instead of a preview

<img src="https://www.wecotec.de/fileadmin/yoasterrror.jpg">

### Technical info
* TYPO3 version: 8.7.24
* Yoast SEO version: 3.05

**Comment by touch5** [comment]
Same with TYPO3 9.5.4 and Yoast 4.0

**Comment by justusmoroni** [comment]
Hey guys,

this is due to some changes in the TYPO3 Core:
https://typo3.org/security/advisory/typo3-core-sa-2018-007/
https://github.com/TYPO3/TYPO3.CMS/commit/c35646c3f7795a4a7b0046a88f146b490fa4883c

Changes like the following are required here:
https://github.com/TYPO3/TYPO3.CMS/commit/21bd3fd762857ff14ad397e5f888f5ae714260d2
https://github.com/TYPO3/TYPO3.CMS/commit/6a26e8d5fa57be4da83b402154452dbb9dbbcd29

We need to change Line 120 in the `app.js` from:
```
Modal.show(title, content);
```
to:
```
Modal.show(title, $(content));
```

I can provide a pull request for that if you'd like.

**Comment by haassie** [comment]
We know. This was already fixed in master (https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/Resources/Public/JavaScript/app.js#L119).

**Comment by haassie** [comment]
This is fixed in the today released version.
