### ISSUE TITLE
Sitemap in other languages always shows default

### ISSUE THREAD

**Issue by w010** [Yoast/Yoast-SEO-for-TYPO3#268]
* [x] I've read and understood the [contribution guidelines](https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/.github/CONTRIBUTING.md).
* [X] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.
I can't generate sitemap of pages for any other language but default. It's not generated on main sitemaps list sitemap.xml, it's not on /sitemap.xml?tx_yoastseo_sitemap=pages&L=1
Languages are working correctly for site frontend.
What else can I try to make it work? Or l10n is not supported in this extension?

### Please describe what you expected to happen and why.
I expect when I add new language record for site, it shows on sitemap.xml list. Or at least when I open sitemap with &L=nn param it generates sitemap for other language.

### How can we reproduce this behavior?
1. Like described above

### Technical info
* TYPO3 version: 8.7.24
* Yoast SEO version: 3.x - 5.0.1
* Relevant extensions in case of a bug:

**Comment by RinyVT** [comment]
This should be based on the domain / path configuration of your additional language.
So for example, if you have the language on a different domain:
English: example.com
German: example.de

The sitemaps should be available example.com/sitemap.xml and example.de/sitemap.xml
If your languages are with paths (f.e. `/` for English and `/de` for German) it should be `/sitemap.xml` and `/de/sitemap.xml`

If these options are not working, could you provide your RealURL configuration since it's v8?

**Comment by rmeeuwissen** [comment]
@w010 Do you have any update related to this issue?

**Comment by RinyVT** [comment]
Closing this issue due to lack of feedback (and the age of the issue), feel free to open a new issue if this still occurs.
