### ISSUE TITLE
Preview not working if root page is a shortcut page

### ISSUE THREAD

**Issue by websi** [Yoast/Yoast-SEO-for-TYPO3#278]
* [x ] I've read and understood the [contribution guidelines](https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/.github/CONTRIBUTING.md).
* [x ] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.

The page preview at TYPO3 9.5.x not working with a root page from type shortcut.
The cHash at FE request ist not valid because TYPO3 resolves the shortcut and checks the cHash parameter with id of shortcut page.
![Bildschirmfoto 2](https://user-images.githubusercontent.com/2857262/60182375-7cb51e80-9824-11e9-9f4a-ee0e22ae4e0c.png)

### Please describe what you expected to happen and why.

The page preview should work without any additional configuration.
Use current page id instead of root page.
https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/Classes/Backend/PageLayoutHeader.php#L355

### How can we reproduce this behavior?
1. Define root page as shortcut
2. Yoast preview not working any more

### Logs
If applicable, add logs to help explain your problem.

### Technical info
* TYPO3 version: 9.5.8
* Yoast SEO version: 5.0.1
* Relevant extensions in case of a bug:

**Comment by DSchaelchli** [comment]
I experience the same problem. Has anyone got an idea, how to fix the problem?

**Comment by haassie** [comment]
So you get an error on the root page (which is defined as a shortcut page type)? Did you add the shortcut doktype to the allowedDoktypes? Because, by default it should not show a snippet preview on a shortcut page.

**Comment by DSchaelchli** [comment]
Thanks for your reply, I changed the setup so I cant tell you if the doktype is in the allowed doktypes, sorry.

Von: Richard Haeser <notifications@github.com>
Gesendet: Donnerstag, 19. September 2019 20:09
An: Yoast/Yoast-SEO-for-TYPO3 <Yoast-SEO-for-TYPO3@noreply.github.com>
Cc: DSchaelchli <dschaelchli@hotmail.com>; Comment <comment@noreply.github.com>
Betreff: Re: [Yoast/Yoast-SEO-for-TYPO3] Preview not working if root page is a shortcut page (#278)


So you get an error on the root page (which is defined as a shortcut page type)? Did you add the shortcut doktype to the allowedDoktypes? Because, by default it should not show a snippet preview on a shortcut page.

**Comment by websi** [comment]
The problem exists on normal pages and not on the shortcut pages.
The configuration "allowedDoktypes" was not extended.

If the root page is defined as shortcut page, the preview for normal page not working.

We has change our setup, so currently we don't have these issue.

**Comment by RinyVT** [comment]
This should be fixed since version 6.0, since we've moved the preview call to a backend AJAX route.
The rootpage is not being called anymore. Just to be sure I've tested this on a 9 installation where the root page is a shortcut, the analysis works.

I'm closing this issue, if this is not correct and there are still issues with this, feel free open a new issue.
