### ISSUE TITLE
The server was not able to access the page to analyse your content

### ISSUE THREAD

**Issue by eduardofrank** [Yoast/Yoast-SEO-for-TYPO3#308]
* [x] I've read and understood the [contribution guidelines](https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/.github/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.
I installed v5.1.1 on a multisite installation running CMS 9.5.9 and the snippet preview shows `The server was not able to access the page to analyse your content`  and the line below that reads `When trying to fetch , a status code was received. Please make sure your server can access the page.' I tried it also on a single site installation running CMS 9.5.7 with the same result. Both installations were doing fine with v5.0.1 of the yoast plugin.

There substantial differences in the way the XHR links with the `type=1480321830&uriToCheck` are built in version 5.0.1, compared to ones in 5.1.0 and 5.1.1, which are shorter in length.

### Please describe what you expected to happen and why.
Under normal operation, the snippet should appear.

### How can we reproduce this behavior?
1. All occurrences were observed in commercial c-panel hosting environments.
2.
3.

### Screenshots
![Screen Shot 2019-10-16 at 2 04 15 PM](https://user-images.githubusercontent.com/14265713/66946087-33c8e600-f01e-11e9-8926-9f34283f4926.png)

### Logs
If applicable, add logs to help explain your problem.

### Technical info
* TYPO3 version: 9.5.9
* Yoast SEO version: 5.1.1, 5.1.0
* Relevant extensions in case of a bug:

**Comment by RinyVT** [comment]
Hi @eduardofrank,

Since 5.0 we have changed something in the way the url gets generated which calls the frontend, this was meant to fix CORS issues within multi-domain installations.
Could you check in your devtools which url gets called (the url with ?type=1480321830 or the name you gave it in your route-enhancer config) and then visit that URL to see what error shows up?

Thanks in advance.

**Comment by eduardofrank** [comment]
Hi @RinyVT,

5.0.1
http://www.domain.com/bca2/?type=1480321830&uriToCheck=http%253A%252F%252Fwww.domain.com%252Fbca2%252F&cHash=4cb666b458ca2f0be3e1cde05e210456

5.1.1
http://domain.com/?type=1480321830&uriToCheck=http%3A%2F%2Fwww.domain.com%2Fbca2%2F
In the part just before `?type`, this url misses on the subdirectory bca2 as well as on the `www`.
Upon clicking on it, the error in the console is `
domain.com/:1 Failed to load resource: the server responded with a status of 503 (Service Unavailable)`. No wonder, the missing subdir already hints to a misconstructed URL.
I hope this helps you further.

**Comment by JesperBom** [comment]
Same problem in typo 8.7.28 with Yoast 5.1.1: https://screencast.com/t/OExdRpxAHVU

The link checked is: 
https://domain.com/?type=1480321830&pageIdToCheck=1&languageIdToCheck=0
And if I open this link in a new tab the content returned seems fine, everything is filled as expected (slug is null tho) but urls and content just fine

Returned:
`{"id":1,"url":"https:\/\/domain.com\/nl-nl","baseUrl":"https:\/\/domain.com\/nl-nl","slug":null,"title":"Website title","description":"","locale":"nl","body":"<!-- TYPO3SEARCH_begin --> and so on....`

**Comment by Jashi** [comment]
Just in case somebody else has the same problem and config as we did in our development environment with TYPO3 8:
We have debugging enabled via config.debug = 1
TYPO3 8 renders the parsetime because of this: 

When I call domain.com/?type=1480321830&pageIdToCheck=1&languageIdToCheck=0&additionalGetVars= like the Yoast preview module, the json I receive ends with this parsetime comment and therefore is invalid and breaks the preview with the error mentioned above. 

The quick fix: disbale debug mode -> config.debug = 0.

**Comment by typecat** [comment]
Another cause might be a feature/ extension that handles redirects and misses to pass additional query arguments so that EXT:yoast_seo didn't know which page id to query for.

In our case it was: 
* TYPO3 8.7.30
* EXT:yoast_seo 5.1.1
* [EXT:shortcut_statuscodes](https://github.com/webit-de/typo3-shortcut_statuscodes/)

[See related issue](https://github.com/webit-de/typo3-shortcut_statuscodes/issues/8)

**Comment by fitli65** [comment]
Hi there,
Any news about this issue?

I have the same behavior in my system:
Typo3: 8.7.32
Yoast_SEO: 5.1.1
simulatestatic: 2.1.0

PS: I updated from 3.0.5 where I had some more modules... Is it normal to have in 5.1.1 only:
Dashboard
Overview
Premium

Thanks in advance and stay healthy in this crazy time ;o)

**Comment by RinyVT** [comment]
Could someone check if this issue is still present in the latest version?
We changed some things in the rendering, for example the subdirectory problem should be fixed.

@fitli65 We removed the "Update" backend module since this is not applicable anymore.

**Comment by eduardofrank** [comment]
Hi Riny,

thanks for contacting me. I have no complaints with the multi-domain site
at this moment.
It is running on CMS 10.4.10, Yoast SEO for TYPO3 is at 7.0.7 and Yoast SEO
for TYPO3 - EXT:news is at 2.1.2. Couldn't find any url with
?type=1480321830 in the console anywhere.
Both Yoast extensions seem to be working.

Cheers

EF

**Comment by RinyVT** [comment]
Thanks for the feedback! I will close this issue for now, if anyone has problems with the newest versions and the content-analyzing, feel free to open a new issue.
