### ISSUE TITLE
Compatability to TYPO3 11

### ISSUE THREAD

**Issue by PhilippKuhlmay** [Yoast/Yoast-SEO-for-TYPO3#450]
Hi is it planned to make this extension compatible with TYPO3 11? The LTS for version 11 isn't far away.
At the moment I can't install it with TYPO3 because of the limitations in composer.json file.

**Comment by RinyVT** [comment]
Hi @PhilippKuhlmay,
We have been working on a new version of the extension since a few months, you could take a look in the feature branch:
https://github.com/Yoast/Yoast-SEO-for-TYPO3/tree/feature/v8
Apart from 11LTS support, there are a lot of other (code-based) changes and still a work-in-progress.

Our original planning was to release this in August, but unfortunately we didn't make it. I hope to release this as soon as possible, in the upcoming weeks!

**Comment by PhilippKuhlmay** [comment]
@RinyVT 
Is there a special issue tracker for TYPO3 11 and the branch feature/v8 or should I create issues inside the repo?

https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/feature/v8/ext_localconf.php#L17 
The constants.typoscript is loaded but the file doesn't exist anymore.

**Comment by RinyVT** [comment]
@PhilippKuhlmay Sorry for the late reply, TYPO3 11 is now officialy supported.
The current 8.0.0 release still has the constants.typoscript include in it, but it has been fixed in the master branch.
I'll release a new version soon (when the PHP8 support is merged).
I'll close the issue for now, feel free to open a new issue if you find anything else.
