### ISSUE TITLE
Inheritance of settings, for example facebook image

### ISSUE THREAD

**Issue by phifa** [Yoast/Yoast-SEO-for-TYPO3#47]
There should be a setting to allow inheritance for subpages, for certain fields. It does not make sense for every field, but for some. If someone wants one global facebook image for example, this should be set on the root page, but should work for all subpages, if not overwritten. There are propably a few fields where this could make sense.

**Comment by haassie** [comment]
How do you think about this @omarreiss ? I can imagine that this will only have an influence on your ranking when done on the wrong fields.

**Comment by omarreiss** [comment]
We do have a default Facebook image as a global setting in Yoast SEO for WordPress because it's always better to have something than nothing. So that could be a feature. 

For the same reason I could imagine it being useful to default to the root page's image in a page tree or to a category's image if that's available. However, we always encourage having unique and tailored content for every page. Sharing OG images between pages therefore isn't necessarily a practice we want to stimulate. I'll check with @jdevalk about this.

**Comment by haassie** [comment]
Any news on this @omarreiss ?

**Comment by tacoverdo** [comment]
Just discussed this with @jdevalk and @haassie.
The ultimate goal should, of course, be unique content for every page. That's why we decided that having just one global 'placeholder' image should suffice.
