### ISSUE TITLE
Errors when copying pages with EXT:yoast_seo_premium

### ISSUE THREAD

**Issue by christophlehmann** [Yoast/Yoast-SEO-for-TYPO3#477]
Version 5 of EXT:yoast_seo_premium misses

`\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::allowTableOnStandardPages('tx_yoast_seo_premium_prominent_words');` in `ext_tables.php` and thus leads to DataHandler errors when copying pages having such records

**Comment by renalpha** [comment]
We experience the same problem.

**Comment by RinyVT** [comment]
Hi,

This is indeed an unfortunate bug introduced with the last major version.
I have fixed this within the Premium extension, the plan is to release the bugfix version next week!

I'll close this issue for now, since this repository is meant for the free version of the extension.
Feel free to contact support@yoast.com in the future for premium bugs / questions :)
