### ISSUE TITLE
InvalidArgumentException Language -1 does not exist on site in InternalLinkingSuggestion

### ISSUE THREAD

**Issue by abvdveen** [Yoast/Yoast-SEO-for-TYPO3#554]
Using Yoast 9.0.1, you get a 503 when trying to edit a CE that uses 'All languages' - id of which is -1.
I 'fixed' this bij adding a condition and returning the default language in case the language id == -1:

```
        if($this->languageId != -1){
            $siteLanguage = $site->getLanguageById($this->languageId);
            return $siteLanguage->getTwoLetterIsoCode();
        }
        else return 'NL';

```

**Comment by RinyVT** [comment]
Hi @abvdveen!

I have actually merged a pull request today that fixes the exception but displays a message that the internal linking suggestions cannot be analyzed because the language is unknown:
https://github.com/Yoast/Yoast-SEO-for-TYPO3/pull/544

I will have a look at the possibility to analyze the default language instead, so I'll keep this issue open :)
